# Generated by Django 6.0.6 on 2026-06-25 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres.')])),
                ('apellidos', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'El apellido debe tener al menos 3 caracteres.')])),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Error: La cédula debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Error: El número de celular debe tener 10 dígitos y empezar con '09'.", regex='^09\\d{8}$')])),
                ('ubicacion', models.CharField(max_length=255)),
                ('nombre_emprendimiento', models.CharField(max_length=200)),
                ('actividad', models.CharField(max_length=200)),
                ('latitud', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0, 'La latitud mínima es -90'), django.core.validators.MaxValueValidator(90.0, 'La latitud máxima es 90')])),
                ('longitud', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0, 'La longitud mínima es -180'), django.core.validators.MaxValueValidator(180.0, 'La longitud máxima es 180')])),
            ],
        ),
    ]
