# Generated by Django 6.0.6 on 2026-06-27 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='cedula',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Error: La cédula debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
    ]
