# Generated by Django 6.0.6 on 2026-06-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emprendimiento_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
    ]
