"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from dotenv import load_dotenv

# Carga las variables de entorno del archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'clave-por-defecto-insegura')

# SECURITY WARNING: don't run with debug turned on in production!
# Leerá True en tu PC, pero en Render lo configuraremos como False
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Permitir conexiones desde cualquier host para evitar bloqueos en Render y Vercel
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    # AÑADIDO: Cloudinary para manejar imágenes antes de los archivos estáticos
    'cloudinary_storage', 
    'django.contrib.staticfiles',
    'cloudinary', 
    
    # Aplicaciones de terceros y locales
    'rest_framework',
    'corsheaders',
    'api', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # AÑADIDO: WhiteNoise para servir archivos estáticos en producción (Render)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# AÑADIDO: dj_database_url conectará con Neon. Si no encuentra la URL, usará sqlite3 por defecto.
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS Y MULTIMEDIA (CLOUDINARY)
# ==============================================================================
STATIC_URL = 'static/'
# Directorio donde Render agrupará los archivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Activa la compresión de archivos estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
MEDIA_URL = '/media/'
# Indica a Django que guarde las imágenes en Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ==============================================================================
# CONFIGURACIÓN DE CORS Y API
# ==============================================================================
# AÑADIDO: Permite peticiones desde cualquier origen (ideal para evitar errores con Vercel)
CORS_ALLOW_ALL_ORIGINS = True 

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# ==============================================================================
# CONFIGURACIÓN DEL SERVIDOR SMTP PARA ENVÍO DE CORREOS
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'geoemprende770@gmail.com'
EMAIL_HOST_PASSWORD = 'ezxs wtpv fece vtus' 
DEFAULT_FROM_EMAIL = f'Geo-Emprende UTC <{EMAIL_HOST_USER}>'